name: Share Regex/Workflow
description: Share your regex rules or workflows
title: "[Country] Description"
labels: [share regex/workflow]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing, the content will be synchronized to the wiki page within a minute.
        If you need to update the content later, just edit this issue.

  - type: textarea
    id: detail
    attributes:
      label: "The regex/workflow"
    validations:
      required: true


