name: Feature request
description: Suggest a new feature
labels: [new feature]
body:

  - type: textarea
    id: feature-description
    attributes:
      label: The feature
    validations:
      required: true

