name: Share Regex
description: Share your regex rules
title: \[Country\] Description
labels: [share regex]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing.

  - type: textarea
    id: detail
    attributes:
      label: The regex
    validations:
      required: true

