  name: Build Nightly
  on: push
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Setup JDK
          uses: actions/setup-java@v4
          with:
            distribution: 'oracle'
            java-version: 1.8

        - name: Build
          run: ./gradlew assembleRelease
